"use client"
import Navigation from "@/components/Navigations";
import "./globals.css";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css"
import { useEffect } from "react";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My next app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  useEffect(() => {
    import("bootstrap/dist/js/bootstrap")
  }, [])

  return (
    <html lang="en">
      <head></head>
      <body>
        <div className="viewport-container">
          <Navigation />
          <div className="content-container">{children}</div>
        </div>

        <style jsx>{`
          body {
            margin: 0;
            padding: 0;
          }

          .viewport-container {
            min-height: 100vh;
            width: 100%;
            background-color: #f2f2f2;
            overflow-y: auto;
          }

          .content-container {
            padding: 20px;
          }
        `}</style>
      </body>
    </html>
  );
}
